//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ASM.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ASMParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IASMVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ASMParser.asm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsm([NotNull] ASMParser.AsmContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ASMParser.base"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBase([NotNull] ASMParser.BaseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ASMParser.commands"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommands([NotNull] ASMParser.CommandsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ASMParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabel([NotNull] ASMParser.LabelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ASMParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommand([NotNull] ASMParser.CommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ASMParser.arithmetic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArithmetic([NotNull] ASMParser.ArithmeticContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ASMParser.control_flow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitControl_flow([NotNull] ASMParser.Control_flowContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ASMParser.tdc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTdc([NotNull] ASMParser.TdcContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ASMParser.num_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNum_list([NotNull] ASMParser.Num_listContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>pushNum</c>
	/// labeled alternative in <see cref="ASMParser.stack"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPushNum([NotNull] ASMParser.PushNumContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>popReg</c>
	/// labeled alternative in <see cref="ASMParser.stack"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPopReg([NotNull] ASMParser.PopRegContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>pushR</c>
	/// labeled alternative in <see cref="ASMParser.stack"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPushR([NotNull] ASMParser.PushRContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>dup</c>
	/// labeled alternative in <see cref="ASMParser.stack"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDup([NotNull] ASMParser.DupContext context);
}
